language: cpp
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:snaipewastaken/ppa ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install criterion-dev ; fi
after_script:
  if: branch == master
  - if [[ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_OS_NAME" == "linux" -a "CXX" == "g++"]]; then wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.5/codacy-coverage-reporter-4.0.5-assembly.jar ; fi
  - if [[ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_OS_NAME" == "linux" -a "CXX" == "g++"]]; then make coverage ; fi
  - if [[ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_OS_NAME" == "linux" -a "CXX" == "g++"]]; then java -jar ~/codacy-coverage-reporter-assembly-latest.jar report --language CPP --force-language -r coverage.xml ; fi
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - lcov
      - gcovr
  homebrew:
    packages:
      - snaipe/soft/criterion
      - lcov
      - gcovr
