language: cpp
before_install:
  - sudo add-apt-repository ppa:snaipewastaken/ppa && sudo apt-get update && sudo apt-get install criterion-dev gcov lcov
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')
after_script:
  - make coverage
  - codacy-coverage-reporter report --language CPP --force-language -r coverage.xml
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
