language: cpp
before_install:
  - sudo add-apt-repository -y ppa:snaipewastaken/ppa && sudo apt-get update && sudo apt-get install -y criterion-dev lcov
  - curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest
  - curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | ruby -r json -e 'print JSON.parse($stdin.read)["assets"][0]["browser_download_url"]'
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | ruby -r json -e 'print JSON.parse($stdin.read)["assets"][0]["browser_download_url"]')
after_script:
  - make coverage
  - codacy-coverage-reporter report --language CPP --force-language -r coverage.xml
compiler:
  - gcc
  - clang
os:
  - linux
