language: cpp
before_install:
  - sudo add-apt-repository ppa:snaipewastaken/ppa && sudo apt-get update && sudo apt-get install criterion-dev gcov lcov
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
